services:
  postgres:
    image: 'postgres:latest'
    container_name: iw-email-sender-container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: iw-email-sender-db
    ports:
      - '5432:5432'
    volumes:
      - iw_email_sender:/var/lib/postgresql/data
    networks:
      - iw_email_sender_net
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  iw_email_sender:

networks:
  iw_email_sender_net:
