spring.application.name=IW Email Sender

spring.liquibase.url=jdbc:postgresql://localhost:5432/iw-email-sender-db
spring.datasource.username= user
spring.datasource.password= pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml



#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=bezbednostinformaciska@gmail.com
#spring.mail.password=qmwfsrxzorezfabc
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true



spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=username
spring.mail.password=pass
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

